# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: imagestack
  toolbox_name: ImageStack              
  author_name: Eivind Hennestad                     
  author_email: eivihe@uio.no         
  author_company: University of Oslo
  toolbox_summary: A class based data model representing image stacks in 5 dimensions
  toolbox_description: |
    A detailed description of your MATLAB toolbox.
    This can span multiple lines to provide users with enough information
    on what your toolbox offers and how it can be used.
  dependencies:
    - MATLAB

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: null
